version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - backend
    networks:
      custom-network:
        aliases:
          - frontend.local
    environment:
      - BACKEND_URL=http://backend.local:3000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      custom-network:
        aliases:
          - backend.local
    environment:
      - DATABASE_URL=sqlite:///var/lib/sqlite3/db.sqlite

  database:
    image: nouchka/sqlite3
    volumes:
      - db-data:/var/lib/sqlite3
    networks:
      custom-network:
        aliases:
          - database.local

volumes:
  db-data:

networks:
  custom-network: